version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: football_app
    ports:
      - "4000:4000"
    volumes:
      # Mount the current directory into the container for hot-reloading
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - ayo_network

  postgres:
    image: postgres:16-alpine
    container_name: football_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: football_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d football_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ayo_network

volumes:
  pgdata:

networks:
  ayo_network:
    driver: bridge
